### ISSUE TITLE
一度でも郵便番号のキャッシュに失敗すると、以降二度と郵便番号検索できない

### ISSUE THREAD

**Issue by BuminMacintosh** [itigoore01/ngx-yubinbango#17]

**Comment by BuminMacintosh** [comment]
例えば 000 から始まるアドレスを入れて検索すると間違ったキャッシュがなされて以降二度と検索が実行できなくなるようです。

**Comment by BuminMacintosh** [comment]
getAddress の this.referenceId.pipe(....) に catchError を入れて throwError を返し、this.addressCache[topPostalCode].pipe(…) に catchError を入れて、null を返すようにすると、エラーも出ずに再検索できるようになりました。

**Comment by itigoore01** [comment]
@BuminMacintosh Issueありがとうございます。
対応しました。

**Comment by BuminMacintosh** [comment]
素早い対応ありがとうございます。
動作確認しましたが、首題の件は解決されていました。

ただ、理由はまだ追っていませんが別の問題が発生してしまったようでして、Issueを挙げさせていただきました。
原因がわかりましたらそちらに追記いたします。

今後共よろしくお願いします。
